version: '3.8'

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      REDIS_URL: "redis://redis:6379"
      TASKS_URL: "0.0.0.0:8080"
    depends_on:
      - redis
    networks:
      - backend_network

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
